LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := framework-res__auto_generated_rro_vendor
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := framework-res__auto_generated_rro_vendor.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := framework-res
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SoftapOverlayWpa3
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SoftapOverlayWpa3/SoftapOverlayWpa3.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TetheringOverlay_Gsi
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := TetheringOverlay_Gsi/TetheringOverlay_Gsi.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SoftapOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SoftapOverlay/SoftapOverlay.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TetheringOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := TetheringOverlay/TetheringOverlay.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
